package eu.europa.ec.eci.oct.validation
global ValidationResult validationResult;
rule "rule_oct.property.personal.number"
    dialect "java"
    when
        v : ValidationProperty(key == "personal.number", value == null || value not matches "([0-9]{8}-[0-9]{4}|[0-9]{6}-[0-9]{4}|[0-9]{12}|[0-9]{10})" )
    then
        validationResult.addValidationError("personal.number","oct.error.propertytypemismatch",ValidationConstants.SKIPPABLE);
end