import { environment } from '../environments/environment';

export const GLOBAL = {
    appTitle: 'eUI-app',
    baseUrl: environment.apiBaseUrl,
    languages: ['en', 'fr'],
    defaultLanguage: 'en',
    availableLanguages: [],
    i18nFolders: ['i18n'],
    languageList: {
        bg: 'български (bg)',
        cs: 'čeština (cs)',
        da: 'dansk (da)',
        de: 'Deutsch (de)',
        et: 'eesti (et)',
        el: 'ελληνικά (el)',
        en: 'English (en)',
        es: 'español (es)',
        fr: 'français (fr)',
        ga: 'Gaeilge (ga)',
        hr: 'hrvatski (hr)',
        it: 'italiano (it)',
        lv: 'latviešu (lv)',
        lt: 'lietuvių (lt)',
        hu: 'magyar (hu)',
        mt: 'Malti (mt)',
        nl: 'Nederlands (nl)',
        pl: 'polski (pl)',
        pt: 'português (pt)',
        ro: 'română (ro)',
        sk: 'slovenčina (sk)',
        sl: 'slovenščina (sl)',
        fi: 'suomi (fi)',
        sv: 'svenska (sv)'
    },
    'documents': {
        'at.passport': 'Reisepass',
        'at.id.card': 'Personalausweis',
        'bg.personal.number': 'Единен граждански номер',
        'cy.id.card': 'Δελτίο Ταυτότητας',
        'cy.passport': 'Διαβατήριο',
        'cz.passport': 'Cestovní pas',
        'cz.id.card': 'Občanský průkaz',
        'fr.passport': 'Passeport',
        'fr.id.card': 'Carte nationale d\'identité',
        'hu.id.card': 'személyazonosító igazolvány',
        'hu.passport': 'útlevél',
        'hu.personal.number': 'személyi azonosító (személyi szám)',
        'it.passport': 'Passaporto',
        'it.id.card': 'Carta d\'identità',
        'ro.id.card': 'carte de identitate',
        'ro.passport': 'pașaport',
        'ro.personal.id': 'Cod Numeric Personal',
        'se.personal.number': 'Personnummer',
        'es.id.card': 'Documento Nacional de Identidad',
        'es.passport': 'Pasaporte',
        'mt.id.card': 'Karta tal-Identità',
        'lt.personal.number': 'Asmens kodas',
        'lv.personal.id': 'Personas kods',
        'pt.id.card': 'Bilhete de identidade',
        'pt.passport': 'Passaporte',
        'pt.citizens.card': 'Cartão de Cidadão',
        'pl.national.id.number': 'Numer ewidencyjny PESEL',
        'si.personal.number': 'Enotna matična številka občana',
        'hr.personal.id': 'Osobni identifikacijski broj',
        'ee.personal.number': 'ISIKUKOOD',
        'be.national.id.number': 'Numéro de Registre national / Rijksregisternummer / Nummer des Nationalregisters'
    }
};
