package eu.europa.ec.eci.oct.validation
global ValidationResult validationResult;
rule "rule_oct.property.id.card"
    dialect "java"
    when
        v : ValidationProperty(key == "id.card", value == null || value.toLowerCase() not matches "[a-z]{2}[0-9]{6}" )
    then
        validationResult.addValidationError("id.card","oct.error.propertytypemismatch",ValidationConstants.SKIPPABLE);
end
rule "rule_oct.property.passport"
    dialect "java"
    when
        v : ValidationProperty(key == "passport", value == null || value.toLowerCase() not matches "[a-z0-9]*")
    then
        validationResult.addValidationError("passport","oct.error.propertytypemismatch",ValidationConstants.SKIPPABLE);
end
rule "rule_oct.property.personal.id"
    dialect "java"
    when
        v : ValidationProperty(key == "personal.id", value == null || value not matches "[0-9]{13}")
    then
        validationResult.addValidationError("personal.id","oct.error.propertytypemismatch",ValidationConstants.SKIPPABLE);
end