package eu.europa.ec.eci.oct.export.model;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.03 at 01:56:07 PM CET 
//



import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.ec.eci.export.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.ec.eci.export.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SignatureListType }
     * 
     */
    public SignatureListType createSignatureListType() {
        return new SignatureListType();
    }

    /**
     * Create an instance of {@link SupportForm }
     * 
     */
    public SupportForm createSupportForm() {
        return new SupportForm();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link SignatoryType }
     * 
     */
    public String createSignatoryType() {
        return new String();
    }

    /**
     * Create an instance of {@link InitiativeDataType }
     * 
     */
    public InitiativeDataType createInitiativeDataType() {
        return new InitiativeDataType();
    }

    /**
     * Create an instance of {@link InformationGroupListType }
     * 
     */
    public InformationGroupListType createInformationGroupListType() {
        return new InformationGroupListType();
    }

    /**
     * Create an instance of {@link PropertyListType }
     * 
     */
    public PropertyListType createPropertyListType() {
        return new PropertyListType();
    }

}
