package eu.europa.ec.eci.oct.export.model;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.03 at 01:56:07 PM CET 
//



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SignatureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignatureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="submissionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="signatureIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="annexRevision" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="signatoryInfo" type="{}SignatoryType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignatureType", propOrder = {
    "submissionDate",
    "signatureIdentifier",
    "annexRevision",
    "signatoryInfo"
})
public class SignatureType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar submissionDate;
    @XmlElement(required = true)
    protected String signatureIdentifier;
    protected int annexRevision;
    @XmlElement(required = true)
    protected SignatoryType signatoryInfo;

    /**
     * Gets the value of the submissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionDate() {
        return submissionDate;
    }

    /**
     * Sets the value of the submissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionDate(XMLGregorianCalendar value) {
        this.submissionDate = value;
    }

    /**
     * Gets the value of the signatureIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureIdentifier() {
        return signatureIdentifier;
    }

    /**
     * Sets the value of the signatureIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureIdentifier(String value) {
        this.signatureIdentifier = value;
    }

    /**
     * Gets the value of the annexRevision property.
     * 
     */
    public int getAnnexRevision() {
        return annexRevision;
    }

    /**
     * Sets the value of the annexRevision property.
     * 
     */
    public void setAnnexRevision(int value) {
        this.annexRevision = value;
    }

    /**
     * Gets the value of the signatoryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SignatoryType }
     *     
     */
    public SignatoryType getSignatoryInfo() {
        return signatoryInfo;
    }

    /**
     * Sets the value of the signatoryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatoryType }
     *     
     */
    public void setSignatoryInfo(SignatoryType value) {
        this.signatoryInfo = value;
    }

}
