package eu.europa.ec.eci.oct.export.model;

//

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.03 at 01:56:07 PM CET 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for InitiativeDataType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="InitiativeDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="registrationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="registrationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="urlOnCommissionRegister" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="organizerList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contactPersonsList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InitiativeDataType", propOrder = {

})
public class InitiativeDataType {

	@XmlElement(required = true)
	protected String registrationNumber;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar startOfTheCollectionPeriod;
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar endOfTheCollectionPeriod;
	@XmlElement(required = true)
	protected String urlOnCommissionRegister;
	@XmlElement(required = true)
	protected String title;
	@XmlElement(required = true)
	protected String objectives;
	@XmlElement(required = true)
	protected String registeredContactPersons;
	@XmlElement(required = true)
	protected String url;

	/**
	 * Gets the value of the registrationNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRegistrationNumber() {
		return registrationNumber;
	}

	/**
	 * Sets the value of the registrationNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRegistrationNumber(String value) {
		this.registrationNumber = value;
	}

	/**
	 * Gets the value of the startOfCollectionPeriod property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getStartOfTheCollectionPeriod() {
		return startOfTheCollectionPeriod;
	}

	/**
	 * Sets the value of the startOfCollectionPeriod property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setStartOfTheCollectionPeriod(XMLGregorianCalendar startOfTheCollectionPeriod) {
		this.startOfTheCollectionPeriod = startOfTheCollectionPeriod;
	}

	/**
	 * Gets the value of the endOfCollectionPeriod property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getEndOfTheCollectionPeriod() {
		return endOfTheCollectionPeriod;
	}

	/**
	 * Sets the value of the endOfCollectionPeriod property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setEndOfTheCollectionPeriod(XMLGregorianCalendar endOfTheCollectionPeriod) {
		this.endOfTheCollectionPeriod = endOfTheCollectionPeriod;
	}

	/**
	 * Gets the value of the urlOnCommissionRegister property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrlOnCommissionRegister() {
		return urlOnCommissionRegister;
	}

	/**
	 * Sets the value of the urlOnCommissionRegister property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUrlOnCommissionRegister(String value) {
		this.urlOnCommissionRegister = value;
	}

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	/**
	 * Gets the value of the content property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getObjectives() {
		return objectives;
	}

	/**
	 * Sets the value of the objectives property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setObjectives(String objectives) {
		this.objectives = objectives;
	}

	/**
	 * Gets the value of the registeredContactPersons property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRegisteredContactPersons() {
		return registeredContactPersons;
	}

	/**
	 * Sets the value of the registeredContactPersons property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRegisteredContactPersons(String registeredContactPersons) {
		this.registeredContactPersons = registeredContactPersons;
	}

	/**
	 * Gets the value of the url property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * Sets the value of the url property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUrl(String value) {
		this.url = value;
	}

}
