package eu.europa.ec.eci.oct.validation
global ValidationResult validationResult;
rule "rule_oct.property.national.id.number"
    dialect "java"
    when
        v : ValidationProperty(key == "national.id.number", value == null || value not matches "[0-9]{11}" )
    then
        validationResult.addValidationError("national.id.number","oct.error.propertytypemismatch",ValidationConstants.SKIPPABLE);
end