package eu.europa.ec.eci.oct.validation
global ValidationResult validationResult;
rule "rule_oct.property.id.card"
    dialect "java"
    when
        sf : ValidationProperty(key == "id.card", value == null || value.toLowerCase() not matches "([0-9]{6}[a-z]{2})|([a-z]{2}[a-z][0-9]{6})|([a-z]{2}[a-z]{2}[0-9]{6})|([a-z]{2}[a-z]{3}[0-9]{6})|([a-z]{2}[0-9]{6})" )
    then
        validationResult.addValidationError("id.card","oct.error.propertytypemismatch", ValidationConstants.SKIPPABLE);
end
rule "rule_oct.property.passport"
    dialect "java"
    when
        v : ValidationProperty(key == "passport", value == null || value.toLowerCase() not matches "([a-z]{2}[0-9]{6})|([a-z]{2}[0-9]{7})")
    then
        validationResult.addValidationError("passport","oct.error.propertytypemismatch", ValidationConstants.SKIPPABLE);
end
rule "rule_oct.property.personal.number"
    dialect "java"
    when
        v : ValidationProperty(key == "personal.number", value == null ||  value not matches "[0-9][0-9]{6}[0-9]{4}" )
    then
        validationResult.addValidationError("personal.number","oct.error.propertytypemismatch", ValidationConstants.SKIPPABLE);
end