package eu.europa.ec.eci.oct.validation
global ValidationResult validationResult;
rule "rule_oct.property.permanent.residence"
    dialect "java"
    when
        v : ValidationProperty(key == "personal.id", value == null || value not matches "[0-9]{6}[0-9]{5}")
    then
        validationResult.addValidationError("personal.id","oct.error.propertytypemismatch", ValidationConstants.SKIPPABLE);
end